name: Add new issues to PatternFly Issues project
on:
  issues:
    types:
      - opened
jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/orgs/patternfly/projects/7
          github-token: ${{ secrets.GH_PROJECTS }}
  label-issue:
    runs-on: ubuntu-latest
    steps:
    - name: Team Membership Checker
      id: teamcheck
      # You may pin to the exact commit or the version.
      # uses: TheModdingInquisition/actions-team-membership@a69636a92bc927f32c3910baac06bacc949c984c
      uses: TheModdingInquisition/actions-team-membership@v1.0
      with:
        # Repository token. GitHub Action token is used by default(recommended). But you can also use the other token(e.g. personal access token).
        token: ${{ secrets.GH_READ_ORG_TOKEN }}
        # The team to check for.
        team: 'frequent-flyers'
        # The organization of the team to check for. Defaults to the context organization.
        organization: 'patternfly'
        # If the action should exit if the user is not part of the team.
        exit: false
              
    - name: Add label if user is a team member
      if: steps.teamcheck.outputs.permitted == 'true'
      run: |
        curl -X POST \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/labels \
          -d '{"labels":["PF Team"]}'
